version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data

volumes:
  postgres:
    name: csb-indexer-db
  redis:
    name: csb-indexer-redis
